services:
  frontend:
    image: nginx:alpine
    restart: unless-stopped
    ports:
      # These two ports must be identical, and must match the one in nginx.conf
      - "8080:8080"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./html:/usr/share/nginx/html
    depends_on:
      - martin
      - maputnik

  maputnik:
    image: ghcr.io/maplibre/maputnik:main
    restart: unless-stopped
    expose:
      - "80"

  martin:
    image: ghcr.io/maplibre/martin:latest
    restart: unless-stopped
    expose:
      - "3000"
    volumes:
      - ./data:/data
    command:
      - /data/estonia.mbtiles
      - /data/benches.mbtiles
      - postgresql://postgres:password@db/estonia
    depends_on:
      - db

  db:
    image: postgis/postgis:16-3.4-alpine
    restart: unless-stopped
    environment:
      - POSTGRES_DB=estonia
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    volumes:
      # persist PostgreSQL data in a local directory outside the docker container
      - ./pg_data:/var/lib/postgresql/data

  osm2pgsql:
    profiles: ["manual"]
    image: iboates/osm2pgsql:latest
    restart: 'no'
    command:
      - -d
      - postgresql://postgres:password@db/estonia
      - -O
      - flex
      - -S
      - /scripts/bicycle_parking.lua
      - /data/estonia-latest.osm.pbf
    environment:
      - DATABASE_URL=postgresql://postgres:password@db
    volumes:
      - ./data:/data
      - ./scripts:/scripts
    depends_on:
      - db
